name: Build Project

on:
  workflow_dispatch:
  push:
    branches: [ new/for2.2 ]
  pull_request:
    branches: [ new/for2.2 ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build CIPX
        run: dotnet publish -p:CreateCipx=true --configuration Release --no-restore

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: classislandinjector-cipx-artifacts
          path: |
            cipx/ClassIslandInjector.cipx